// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCq3ak-dtM5Dh7IgPqRT8FAStrofh34q-U',
    appId: '1:661905295202:web:03ac43f9c202f725eece3b',
    messagingSenderId: '661905295202',
    projectId: 'msapp-f24bb',
    authDomain: 'msapp-f24bb.firebaseapp.com',
    storageBucket: 'msapp-f24bb.appspot.com',
    measurementId: 'G-DS4PHBZCLW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMLw0x1TGtyVUVEYPY6z21C2s0CDtx6XU',
    appId: '1:661905295202:android:c0b90ee07813cbf8eece3b',
    messagingSenderId: '661905295202',
    projectId: 'msapp-f24bb',
    storageBucket: 'msapp-f24bb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDl8ScYLDGVsmRtIgmpkhSqx-RmLrYuBvg',
    appId: '1:661905295202:ios:b49fce66e897b0dfeece3b',
    messagingSenderId: '661905295202',
    projectId: 'msapp-f24bb',
    storageBucket: 'msapp-f24bb.appspot.com',
    iosBundleId: 'com.example.msApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDl8ScYLDGVsmRtIgmpkhSqx-RmLrYuBvg',
    appId: '1:661905295202:ios:b49fce66e897b0dfeece3b',
    messagingSenderId: '661905295202',
    projectId: 'msapp-f24bb',
    storageBucket: 'msapp-f24bb.appspot.com',
    iosBundleId: 'com.example.msApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCq3ak-dtM5Dh7IgPqRT8FAStrofh34q-U',
    appId: '1:661905295202:web:0c83761a5c2d54ceeece3b',
    messagingSenderId: '661905295202',
    projectId: 'msapp-f24bb',
    authDomain: 'msapp-f24bb.firebaseapp.com',
    storageBucket: 'msapp-f24bb.appspot.com',
    measurementId: 'G-LZDB467PPN',
  );

}